prometheus_boshrelease_version: '18.6.2'
prometheus_boshrelease_file: prometheus-18.6.2.tgz
node_exporter_boshrelease_version: '2.0.0'
node_exporter_boshrelease_file: node-exporter-2.0.0.tgz
postgres_boshrelease_version: '20'
postgres_boshrelease_file: postgres-release-20.tgz
routing_boshrelease_version: '0.163.0'
routing_boshrelease_file: cf-routing-release-0.163.0.tgz
stemcell_version: '3445'
