prometheus_boshrelease_version: '19.0.0'
prometheus_boshrelease_file: prometheus-19.0.0.tgz
node_exporter_boshrelease_version: '2.0.0'
node_exporter_boshrelease_file: node-exporter-2.0.0.tgz
postgres_boshrelease_version: '21'
postgres_boshrelease_file: postgres-release-21.tgz
routing_boshrelease_version: '0.165.0'
routing_boshrelease_file: cf-routing-release-0.165.0.tgz
stemcell_version: '3445'
