prometheus_boshrelease_version: '21.1.0'
prometheus_boshrelease_file: prometheus-21.1.0.tgz
node_exporter_boshrelease_version: '3.0.1'
node_exporter_boshrelease_file: node-exporter-3.0.1.tgz
postgres_boshrelease_version: '25'
postgres_boshrelease_file: postgres-release-25.tgz
routing_boshrelease_version: '0.171.0'
routing_boshrelease_file: cf-routing-release-0.171.0.tgz
stemcell_version: '3468'
